# Generated by Django 3.2.4 on 2022-03-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesla_ce', '0022_auto_20211124_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='session',
            field=models.ForeignKey(blank=True, default=None, help_text='Related assessment session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesla_ce.assessmentsession'),
        ),
    ]
